CREATE OR REPLACE FUNCTION GET_CSTMR_NAME(IN_CUST_ID NUMBER) RETURN VARCHAR2 AS

VAR_OUTPUT VARCHAR2(100);

BEGIN
    SELECT A.CUST_NAME||' '||B.ADDRESS INTO VAR_OUTPUT FROM MASTER_CUST A, CUST_ADDRESS B
    WHERE A.ADDR_ID = B.ADDRESS_ID AND A.CUST_ID = IN_CUST_ID;
    DBMS_OUTPUT.PUT_LINE(VAR_OUTPUT);
RETURN VAR_OUTPUT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Customer with id: '|| IN_CUST_ID||' not found');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error in getting customer name');    
END;

