CREATE TABLE master_cust (
    cust_id        NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    cust_name      VARCHAR2(100),
    addr_id     NUMBER,
    CONSTRAINT fk_address FOREIGN KEY(addr_id)
    REFERENCES cust_address(address_id)
);